### ISSUE TITLE
Doesn't work on PSTV

### ISSUE THREAD

**Issue by SonyUSA** [yifanlu/usbmc#1]
- Using Enso that supports ur0:tai/config.txt and latest Henkaku build (did R reinstall)
- USB stick works fine manually mounted through Vitashell 
- Other plugins (download-enabler and adrenaline) work fine copied and launched from ur0:tai/*
- External stick is 32GB FAT32 (x1800modmy360x says his is exFAT)

PSTV boots to 640x480 resolution (I'm guessing from triggering safe mode?) but is otherwise functional, however USB stick is not mounted as ux0: . x1800modmy360x says his does NOT go to 480, however his does not mount either with this plugin.

A strange side note, Vitashell seems to be able to mount as uma0: without needing to re-plug in the USB stick (usually needed if plugged in before you choose to mount it).

[config.txt](https://github.com/yifanlu/usbmc/files/1116869/config.txt)

**Comment by ghost** [comment]
Config you posted is wrong. Not sure is just accident, or you used it for test. 

#ur0:tai/usbmc.skprx 

You should remove **#** sign, because it mean that line is commented, and taihen is not load plugin then.

**Comment by SonyUSA** [comment]
I know, I commented it out because if I don't then I get the problems I listed above.

**Comment by yoshi314** [comment]
confirming the odd resolution glitch and mounting issues. same behavior with vitashell.

**Comment by CelesteBlue-dev** [comment]
@yifanlu  Have you (or TheFloW) tested if that plugin was working, at least once ?
Were the old commits working ?

**Comment by yifanlu** [comment]
I've only tested on oled vita.

**Comment by CelesteBlue-dev** [comment]
@yifanlu I add more infos : 
On PSTV with enso : 
- this plugin is not working (let's try to make it working)
- there is no need to bypass ksceSblAimgrIsDolce() as it is really Dolce (PSTV)
- it seams that the check returns that neither sdstor0:uma-pp-act-a nor sdstor0:uma-lp-act-entire exists
- I tried ksceIoMount(0xF00, NULL, 0, 0, 0, 0); but returns error 8100 0002
I think that at the time this kplugin is running, the USB mass is not powered.
That would explain why ksceIoMount(0xF00, NULL, 0, 0, 0, 0); fails and why sdstor0:uma-pp-act-a nor sdstor0:uma-lp-act-entire cannot be accessed.
