### ISSUE TITLE
3.65 kernel plugin is not supported

### ISSUE THREAD

**Issue by Hking0036** [yifanlu/usbmc#18]
When you open the installer, it says that enso but be installed and not deactivated and gives no further options. I think this is because it checks enso by looking for ur0:tai/boot_config.txt which has now been moved to vs0:.

I installed the plugin myself on ur0 and ux0 (internal storage, not flash drive) and rebooted, and it just doesn't seem to find the flash drive.

**Comment by yifanlu** [comment]
Installer issue aside, did it work for you on 3.60?

**Comment by Hking0036** [comment]
Yes, I used it on 3.60 before updating and it worked perfectly.  Mounting to uma0: and then changing to ux0: on vitashell works fine on 3.65.

**Comment by yifanlu** [comment]
Can you try this?
[usbmc.skprx.zip](https://github.com/yifanlu/usbmc/files/1804650/usbmc.skprx.zip)

**Comment by Hking0036** [comment]
Sure thing, give me a minute. I can shoot you a PR on the installer but I've no clue if that will actually fix it and I don't have vitaSDK installed to check at the moment, either.

**Comment by HunterKing** [comment]
seems to be no dice on that plugin as well.

**Comment by Hking0036** [comment]
seems no dice on that plugin as well.

**Comment by yifanlu** [comment]
I got the installer covered. If the plugin doesn't work, then more work needs to be done.

**Comment by erfg12** [comment]
I can compile if necessary. I have a PSVSD Vita on 3.65 and PSTV with a USB thumbdrive.

**Comment by yifanlu** [comment]
I suspect the issue is with the nid changes. Once that's addressed, it might work.

**Comment by AyanamiRei1** [comment]
Man that's good news I really want to get back into using my Vita TV

**Comment by yifanlu** [comment]
To be clear, I have no intention of updating this. If someone fixes it and sends a pull request I can build it.

**Comment by IDBurner** [comment]
So it is interesting.

I had to modify the latest push from TheFlow to get the plugin compiled. Once compiled and the installer modified to point to the new enso directory everything seems to go fine.

However after install and reboot there is no uma directory for the PSVSD . If I go back to the installer, it recognizes the USB drive, shows me the space on it, and copies everything over. On reboot thought it still does not show in the list.

I am not 100% sure this is an issue with the plugin at the moment, but will continue to look into it.

**Comment by Akuma540** [comment]
@IDBurner  would you share the compiled version of yours, so I can test it?

**Comment by yifanlu** [comment]
Does USB storage work in VitaShell? If so, look at what changes were needed there and port them over.

**Comment by IDBurner** [comment]
@yifanlu I am looking at the fork of SD2VITA and porting those over. There is additional work to get uma mounted now.

@Akuma540 I can but they really won't work. There is additional work I see now.

**Comment by Akuma540** [comment]
@yifan lu yes USB Storage for psvsd is working while using Vitashell 1.82.

**Comment by TheOfficialFloW** [comment]
Compile and test this, it should work: https://github.com/yifanlu/usbmc/pull/19

**Comment by IDBurner** [comment]
@TheOfficialFloW 

I had to remove the following
 in order to compile

`if (exists("ux0:tai/config.txt")) {
		taiReloadConfigForKernel(1, 1);
}`

However it is having the same issue I have been running into.

ie The installer sees the device but VitaShell does not

**EDIT**: I have attached my compiles if anyone wants to see if it is just an issue with my Vita
[usbmc.zip](https://github.com/yifanlu/usbmc/files/1807962/usbmc.zip)

**Comment by IDBurner** [comment]
Well shit, it is working lol.

I used the installer to do everything as normal and ran it a second time to make the PSVSD the primary memory card per normal instructions. Everything seems working

**Comment by TheOfficialFloW** [comment]
@IDBurner yeah and you have to download the newest package of taihen https://github.com/vitasdk/packages/commit/451b4d2f143ca762b5791d9d47dc517c02f8456d in order to compile the code.

**Comment by IDBurner** [comment]
Well @TheOfficialFloW you beat me to it. You really should sleep sometime you know :p 

Thanks.

**Comment by erfg12** [comment]
@IDBurner so the usbmc.zip works with the installer on 3.65?

**Comment by IDBurner** [comment]
@erfg12 Yes the installer works on 3.65 

Please note that I was unable to use the PSVSD as a SECONDARY drive (ie with memory card installed as uma mount)

I could only get it working as PRIMARY (ie no official memory card in and as ux mount)

**Comment by Akuma540** [comment]
@IDBurner @TheOfficialFloW  Its working for me, just with the installer. you saved many peoples Vita :D

**Comment by IDBurner** [comment]
@Akuma540 well @TheOfficialFloW  saved many people's Vitas lol. 

I only compiled his fix, he was a lot quicker at it than I. :p
