### ISSUE TITLE
App updates and PKGJ downloads not happening

### ISSUE THREAD

**Issue by smokeofc** [yifanlu/usbmc#22]
Using this on PSTV (3.65 ENSO, 128GB USB Thunb drive (exFAT)), and there are a few issues:

1. Application updates not installing
When updating an app, the update downloads OK, but never installs even when trying to do so manually (pressing the update button in the livearea or notification).

2. Downloads to UX0 not happening
Only really tested using PKGJ. When downloading apps using PKGJ it seems to be working, but doesn't write to UX0:\app

**Comment by yifanlu** [comment]
No support is provided for pirates.
