### ISSUE TITLE
Issue with 3.65

### ISSUE THREAD

**Issue by Darkomg** [yifanlu/usbmc#23]
i update to 3.65, so install the plugin, and then follow the instructions, in order to make the micro SD 3G adapter work as principal memory, here comes the problem, vitashell isnt work after this, i try to use molecularshell to install vitashell again, and keep not working, send me an error (specifically c1-2753-7) i decide to reinstall vitashell then, so i erase vitashell and when im use molecular to try to reinstall, send me error 0x80010016, now i dont have vitashell, just molecularshell, i dont know why its this happen

excuse my english please

**Comment by jmota** [comment]
Launch Molecular shell and navigate to the root. Under ux0: look for a vitashell folder. Delete that folder and reboot.
Then launch molecular shell again and attempt to install vita shell.

You should be good to go. Let me know if that does not work.

Best,
 Jonathan

"90% of what is considered "impossible" is, in fact, possible. The other 10% will become possible with the passage of time & technology." - Hideo Kojima.

**Comment by Darkomg** [comment]
kinda solve the problem, but not with your method, i restart the console and do not start, just black screen, i remove the battery and then connect it again, so the console start as usual, repeat alla the process, unistall usbmc plugin, reinstall vitashell, reinstall plugin, and now aparently all work fine.

thanks for the help, dont know if i can ask throught this media but, ¿is there a way to use 3G adapter AND sony original memory?

**Comment by jmota** [comment]
Glad it worked out, on your follow up inquiry, I have not seen a way to do so. I’ll have to look into that.

Best,
 Jonathan

"90% of what is considered "impossible" is, in fact, possible. The other 10% will become possible with the passage of time & technology." - Hideo Kojima.

**Comment by DasKatzchen** [comment]
Celeste-blue's storage manager plugin will mount multiple storage mediums at multiple mount points. You can't have more than one medium per mount point.

**Comment by Darkomg** [comment]
in 3.60 i used M1lk4h0l1c`s usbmc mod, so i can have psvsd as main ux0 and original memory as uma0, im looking for something like that on 3.65

**Comment by yifanlu** [comment]
This is not a support forum.
