### ISSUE TITLE
Are tai plugins loaded from USB or not?

### ISSUE THREAD

**Issue by DownloadMoreRem** [yifanlu/usbmc#24]
There seem to be conflicting information.

[README says that tai plugins from USB will not be loaded](https://github.com/yifanlu/usbmc/blob/8798df35216f54e4405d04861716fc4f2b2ce2b4/README.md):

>Note: When using USB storage as memory, make sure all taiHEN plugins are installed to ur0: with ur0:tai/config.txt as the config file. This is because taiHEN is loaded before usbmc so you cannot use taiHEN plugins installed to USB.

[Release notes say that tai plugins from USB will be loaded](https://github.com/yifanlu/usbmc/releases/tag/v5):

>Added plugin loading from ux0:tai/config.txt (where ux0 is the newly mounted USB storage). If that file exists, when the plugin is loaded, it will tell taiHEN to use that file instead of ur0:tai/config.txt

So, are tai plugins loaded from USB or not?

**Comment by yifanlu** [comment]
Sorry the readme is outdated.
