### ISSUE TITLE
Not working. 

### ISSUE THREAD

**Issue by dmjohn0x** [yifanlu/usbmc#3]
Pretty sure I followed the newest build to a T, yet I still have to manually mount my USB as ux0. Was there something left out of the instructions?

**Comment by yoshi314** [comment]
It worked for me. Make sure you have no other config.txt in tai folder on other devices.

**Comment by yifanlu** [comment]
Might have to readjust the timeout. Can you try this https://github.com/yifanlu/usbmc/releases/download/v2/usbmc-5sec.skprx

(Rename to usbmc.skprx)

**Comment by ValadAmoleo** [comment]
Using the usbmc-5sec file works perfect for me.

I'm using a USB HDD connected via a y-cable.

Thanks for the fix.

**Comment by yifanlu** [comment]
Okay, I'll bump put the detection time.

**Comment by WilsonHQ** [comment]
I have the same problem and try to download the 5sec version but it has been removed. Can someone make the 5 sec version available again for download. Thanks for the effort.
