### ISSUE TITLE
Please add warning about os0

### ISSUE THREAD

**Issue by Catmato** [yifanlu/usbmc#4]
It's too late for me, but please add something explaining what the os0 modification thing means and what happens when you accept what its asking.  Maybe tell people to disable version spoofing.  My PSTV is already deactivated because of the firmware reinstall, I just want to keep it from happening to others.

**Comment by CelesteBlue-dev** [comment]
Please @Catmato explain better what has happened to you.

**Comment by Catmato** [comment]
After installing and running USBMC, it said something about os0 modifications and prompted something about firmware which I accepted.  I can't go back to look what it asked, but it reinstalled 3.60 firmware and deactivated my PSTV from PSN.  

I guess something else could have caused deactivation, but installing Enso and usbmc are the only two things that I did.

**Comment by CelesteBlue-dev** [comment]
Was it that screen ?
![20170731_141017](https://user-images.githubusercontent.com/20444249/28777111-183e1a04-75fa-11e7-9beb-384301520020.jpg)

**Comment by Catmato** [comment]
Yeah, that's what it said.  I realize that it was my mistake to accept it, bit I didn't realize that would cause deactivation.  Instead of offering to reinstall 3.60, maybe it should suggest to remove version spoofing or spoof back to 3.60.

**Comment by yifanlu** [comment]
Reinstalling 3.60 does not deactivate your console. Something else did that.

**Comment by yifanlu** [comment]
Also wtf that isn't usbmc.

**Comment by Catmato** [comment]
Wow, okay, that is just Enso.  My mistake.
