### ISSUE TITLE
Reload config.txt and plugins on newly mounted ux0:

### ISSUE THREAD

**Issue by TheOfficialFloW** [yifanlu/usbmc#5]
So plugins can be loaded from USB stick.

**Comment by yifanlu** [comment]
Yeah I thought about it before. The only catch is that if you have the same plugin in both ur0:tai/config.txt as well as ux0:tai/config.txt then it will be loaded twice. Although I'm not sure that's too much of an issue. I'll consider updating it that way.

**Comment by TheOfficialFloW** [comment]
If I remember correctly, loading the same module (same nid and version) would result in an "already loaded" error.

**Comment by yifanlu** [comment]
taiHEN needs to be updated for this to work https://github.com/yifanlu/taiHEN/issues/75
