### ISSUE TITLE
Doesnt automount as MemoryCard

### ISSUE THREAD

**Issue by gotbletu** [yifanlu/usbmc#6]
Hey thanks for this project.

Pretty much did everything on the readme.
It does not automount my hard drive as a memory card on bootup though.

I still have to open the VitaShell and manually mount the hard drive as memory card.
One thing that does work is i don't have to reattach my USB cable everytime i want to mount the hard drive anymore. So i guess it half works? =)

----
PSTV 3.60 Enso Henkaku
External Powered 3.5" 1TB Hard Drive

**Comment by yifanlu** [comment]
Same underlying issue as #10
