### ISSUE TITLE
psvsd v2.1 Reset Console can't pass initial setup

### ISSUE THREAD

**Issue by bam2000** [yifanlu/usbmc#7]
Hey,
i have installed you psvsd card and swapped it out for the 3G Modem Card.
I had to reset my console and now I'm stuck in the initial console setup, after entering the Date and Time I only get the world cube and an error message saying there is a problem with the UMTS module (true because it is now longer installed) so I installed it again and now I just see the world cube and nothing more happens... any idea what I can do ???
Is it because I have installed usbmc in Ur0:/tai? so it disables the UMTS module completely?
My Console still have installed Taikaku? Or is it removed by resetting the console to factory?
Please help

**Comment by yifanlu** [comment]
You need to run the uninstaller (see https://github.com/yifanlu/usbmc/blob/master/README.md)

However if you reset your system to factory settings, it should have worked as well. Are you sure your 3G card is plugged in properly and everything is hooked up (like the SIM card slot)?

**Comment by bam2000** [comment]
hey thanks for the answer.
The Problem is i can't complete the initial Setup of my vita. so i can't install your VPK to uninstall USBMC... i have installed the 3G Modem Card and Sim Card adapter but it still stuck without an error message after entering the Time and Date. I can see the Tai logo on bootup, i think tai will load the USBMC on boot and so it disables the UMTS Card and the initial Playstation Vita installation Process needs the UMTS Card to be recognized in order to continue to the home screen?

Maybe possible to Update/install the Firmware to 3.60 again with the Recovery Mode and PC Update ? Then i will lose Tai, but i can complete the Installation Process of the VitaOS and install Tai again after i can use my Vita again :D

**Comment by yifanlu** [comment]
Yeah remove psvsd, put everything back and reinstall 3.60
