### ISSUE TITLE
Not working via powered USB hub connected to VitaTV

### ISSUE THREAD

**Issue by rsn8887** [yifanlu/usbmc#9]
The plugin doesn’t mount the USB stick when it is connected to a powered USB hub instead of directly to the VitaTV.

**Comment by yifanlu** [comment]
I mean that sucks but there's like nothing I can go on here.

**Comment by rsn8887** [comment]
I should have elaborated more. Here are some details:
- I connect a powered usb hub to the VitaTV and the usb stick to the hub.
- I then turn on the VitaTV.
-> the usb stick flashes shortly during boot time, but it is not mounted.

On the other hand
- I connect the usb stick to the VitaTV directly, start the VitaTV, and the stick is correctly mounted
- I now disconnect the stick while the VitaTV is running, connect the usb stick to the Hub, and then connect the hub to the VitaTV
-> now the usb stick keeps working, I can run apps from it etc, even though it is connected to the hub.

Therefore the problem is not he stick or the hub, but something during the mounting at boot that causes it to fail. Maybe not enough time allowed during boot to detect hub+stick? I am using the latest version of boot the plugin.

Edit: hmm it works every once in a while. I just rebooted a few times and one time it mounted correctly. Out of 20 boots it mounted correctly only once. Maybe it is a slow stick and needs one more second or so to allow enough time for hub plus stick to be recognized.

By itself the stick always mounts correctly at boot time. But when connected to the hub it only works every once in a while. The hub is a regular powered Amazonbasics usb 3 hub with 4 ports.

**Comment by rsn8887** [comment]
I found out something else: Everything works perfectly if I don’t power the hub but let it be powered by the Vita.

So somehow the problem is related to whether the hub is powered or not. I wonder if the method used to detect the stick during boot time relies on turning the power to it off and back on? This would explain why it doesn’t work when there’s external power to the hub.

**Comment by rsn8887** [comment]
It was the hub. I bought a second, different hub. The new one is an Amazonbasics 10 port USB 2.0 powered hub. It works perfectly.

The one that shows problems is the Amazonbasics 4 port powered USB 3.0 hub.

Since it is a problem with only one particular powered hub, I will close the issue.
